# Generated by Django 4.2.1 on 2023-05-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='domestico',
            field=models.BooleanField(default='n/a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='nome',
            field=models.CharField(default='n/a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='predador',
            field=models.BooleanField(default='n/a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='venenoso',
            field=models.BooleanField(default='n/a'),
            preserve_default=False,
        ),
    ]
